# origin_clean
# ==============================================================================
#  Add country_1 and country_2 columns to the coffea bean dataset
#  Maps every region/sub-region/growing-zone value to its parent country
# ==============================================================================
library(dplyr)

origin_clean <- function(d){


# ------------------------------------------------------------------------------
# 1.  Read data
# ------------------------------------------------------------------------------
d <- read.csv("Question1/data/regions.csv", stringsAsFactors = FALSE)


# ------------------------------------------------------------------------------
# 2.  Region → Country lookup table
#     Keys are trimmed, title-cased to match after normalisation (see step 3).
# ------------------------------------------------------------------------------
region_to_country <- c(
  
  # ── ALREADY A COUNTRY ────────────────────────────────────────────────────────
  "Bolivia"                              = "Bolivia",
  "Brazil"                               = "Brazil",
  "Brazil And Four Other Origins"        = "Brazil",
  "Burundi"                              = "Burundi",
  "China"                                = "China",
  "Colombia"                             = "Colombia",
  "Columbia"                             = "Colombia",
  "Congo"                                = "Democratic Republic of Congo",
  "Costa Rica"                           = "Costa Rica",
  "Democratic Republic Of Congo"         = "Democratic Republic of Congo",
  "Democratic Republic Of The Congo"     = "Democratic Republic of Congo",
  "Drc Congo"                            = "Democratic Republic of Congo",
  "Ecuador"                              = "Ecuador",
  "El Salvador"                          = "El Salvador",
  "Ethiopia"                             = "Ethiopia",
  "Ethopia"                              = "Ethiopia",
  "Guatemala"                            = "Guatemala",
  "Haiti"                                = "Haiti",
  "Honduras"                             = "Honduras",
  "India"                                = "India",
  "Indonesia"                            = "Indonesia",
  "Jamaica"                              = "Jamaica",
  "Kenya"                                = "Kenya",
  "Madagascar"                           = "Madagascar",
  "Malaysia"                             = "Malaysia",
  "Mexico"                               = "Mexico",
  "Nicaragua"                            = "Nicaragua",
  "Panama"                               = "Panama",
  "Panana"                               = "Panama",
  "Papua New Guinea"                     = "Papua New Guinea",
  "Peru"                                 = "Peru",
  "Philippines"                          = "Philippines",
  "The Philippines"                      = "Philippines",
  "Rwanda"                               = "Rwanda",
  "South Africa"                         = "South Africa",
  "Sumatra"                              = "Indonesia",
  "Taiwan"                               = "Taiwan",
  "Tanzania"                             = "Tanzania",
  "Thailand"                             = "Thailand",
  "Uganda"                               = "Uganda",
  "Vietnam"                              = "Vietnam",
  "Yemen"                                = "Yemen",
  "Zambia"                               = "Zambia",
  
  # ── BROAD CONTINENTAL / MULTI-COUNTRY (kept descriptive) ────────────────────
  "Africa"                               = "Africa (multi-country)",
  "Asia"                                 = "Asia (multi-country)",
  "Asia Pacific"                         = "Asia Pacific (multi-country)",
  "Americas"                             = "Americas (multi-country)",
  "Central America"                      = "Central America (multi-country)",
  "Central And South America"            = "South America (multi-country)",
  "Indo-Pacific"                         = "Asia Pacific (multi-country)",
  "Latin America"                        = "Latin America (multi-country)",
  "South America"                        = "South America (multi-country)",
  "Not Disclosed"                        = "Unknown",
  
  # ── BRAZIL ───────────────────────────────────────────────────────────────────
  "Alto Caparaó"                         = "Brazil",
  "Bahia"                                = "Brazil",
  "Bahia State"                          = "Brazil",
  "Carmo De Minas Growing Region"        = "Brazil",
  "Cerrado Growing Region"               = "Brazil",
  "Cerrado Mineiro"                      = "Brazil",
  "Chapada Diamantina Growing Region"    = "Brazil",
  "Chapada Diamantina Region"            = "Brazil",
  "Eastern Minas Gerais State"           = "Brazil",
  "Ibicoara Municipality"                = "Brazil",
  "Ipanema"                              = "Brazil",
  "Mantiqueira De Minas Growing Region"  = "Brazil",
  "Matas De Minas Growing Region"        = "Brazil",
  "Minas Gerais State"                   = "Brazil",
  "Mogiana"                              = "Brazil",
  "Mogiana Growing Region"               = "Brazil",
  "Northeastern Minas Gerais State"      = "Brazil",
  "Santo Antônio Do Amparo"              = "Brazil",
  "São Paulo State"                      = "Brazil",
  "Sao Paulo State"                      = "Brazil",
  "São Sebastião Da Grama"              = "Brazil",
  "São Sebastião De Grama"              = "Brazil",
  "Southeastern Brazil"                  = "Brazil",
  "Serra Da Mantiqueira"                 = "Brazil",
  "Sul De Minas"                         = "Brazil",
  "Sul De Minas Growing Region"          = "Brazil",
  "Vale Da Grama"                        = "Brazil",
  "Vale De Grama"                        = "Brazil",
  "Southern Minas Gerais State"          = "Brazil",
  
  # ── BOLIVIA ──────────────────────────────────────────────────────────────────
  "Caranavi"                             = "Bolivia",
  "Caranavi Province"                    = "Bolivia",
  
  # ── BURUNDI ──────────────────────────────────────────────────────────────────
  "Buhinyuza District"                   = "Burundi",
  "Bururi Growing Region"                = "Burundi",
  "Buyenzi"                              = "Burundi",
  "Gitega Province"                      = "Burundi",
  "Kayanza"                              = "Burundi",
  "Kayanza Province"                     = "Burundi",
  "Kayanza State"                        = "Burundi",
  "Muhinga Province"                     = "Burundi",
  "Muyinga Province"                     = "Burundi",
  "Ngozi Province"                       = "Burundi",
  "Northern Burundi"                     = "Burundi",
  
  # ── CHINA ────────────────────────────────────────────────────────────────────
  "Yunnan Province"                      = "China",
  
  # ── COLOMBIA ─────────────────────────────────────────────────────────────────
  "Acevedo"                              = "Colombia",
  "Algeciras"                            = "Colombia",
  "Antioquia"                            = "Colombia",
  "Antioquia Department"                 = "Colombia",
  "Antoquia"                             = "Colombia",
  "Aratoca"                              = "Colombia",
  "Armenia"                              = "Colombia",
  "Buesaco"                              = "Colombia",
  "Caicedo"                              = "Colombia",
  "Caicedonia"                           = "Colombia",
  "Caldas"                               = "Colombia",
  "Caldas Department"                    = "Colombia",
  "Caldas Growing Region"                = "Colombia",
  "Campestre"                            = "Colombia",
  "Cauca"                                = "Colombia",
  "Cauca Department"                     = "Colombia",
  "Center-West Colombia"                 = "Colombia",
  "Central Colombia"                     = "Colombia",
  "Cundinamarca"                         = "Colombia",
  "Cundinamarca Department"              = "Colombia",
  "Gaitania"                             = "Colombia",
  "Giraldo"                              = "Colombia",
  "Huila"                                = "Colombia",
  "Huila Colombia"                       = "Colombia",
  "Huila Department"                     = "Colombia",
  "Huila Province"                       = "Colombia",
  "Inza"                                 = "Colombia",
  "La Argentina"                         = "Colombia",
  "La Fundadora"                         = "Colombia",
  "La Mesa"                              = "Colombia",
  "La Palma"                             = "Colombia",
  "Las Margaritas"                       = "Colombia",
  "Liboriana Valley"                     = "Colombia",
  "Manizales"                            = "Colombia",
  "Narino Department"                    = "Colombia",
  "Nariño"                               = "Colombia",
  "Nariño Department"                    = "Colombia",
  "Nariño Region"                        = "Colombia",
  "Neira"                                = "Colombia",
  "Northwest Colombia"                   = "Colombia",
  "Paez Region"                          = "Colombia",
  "Paéz"                                 = "Colombia",
  "Palestina Region"                     = "Colombia",
  "Pasto"                                = "Colombia",
  "Piendamó"                             = "Colombia",
  "Pijao"                                = "Colombia",
  "Pitalito"                             = "Colombia",
  "Pitalito Growing Region"              = "Colombia",
  "Pitalito Municipality"                = "Colombia",
  "Pitalito-Bruselas"                    = "Colombia",
  "Planadas"                             = "Colombia",
  "Quindio Department"                   = "Colombia",
  "Quindío Department"                   = "Colombia",
  "Risaralda"                            = "Colombia",
  "Risaralda Department"                 = "Colombia",
  "Salgar Municipality"                  = "Colombia",
  "San Agustín"                          = "Colombia",
  "San Agustín Growing Region"           = "Colombia",
  "San Augustin"                         = "Colombia",
  "San Augustín"                         = "Colombia",
  "Santander"                            = "Colombia",
  "Santander Department"                 = "Colombia",
  "Sevilla"                              = "Colombia",
  "Southern Colombia"                    = "Colombia",
  "Southern Tolima Department"           = "Colombia",
  "Southern Tolima Growing Region"       = "Colombia",
  "Suaza"                                = "Colombia",
  "Tolima"                               = "Colombia",
  "Tolima Department"                    = "Colombia",
  "Trujillo"                             = "Colombia",
  "Urrao"                                = "Colombia",
  "Valle De Cauca"                       = "Colombia",
  "Valle De Cauca Department"            = "Colombia",
  "Valle Del Cauca"                      = "Colombia",
  "Valle Del Cauca Department"           = "Colombia",
  "Valle Del Cauca Growing Region"       = "Colombia",
  "Vereda"                               = "Colombia",
  "Vereda Santa Rita"                    = "Colombia",
  "West-Central Colombia"                = "Colombia",
  "Southwestern Colombia"                = "Colombia",
  "Southwestern Colombianar"             = "Colombia",
  
  # ── COSTA RICA ───────────────────────────────────────────────────────────────
  "Alajuela"                             = "Costa Rica",
  "Alajuela Province"                    = "Costa Rica",
  "Biollet"                              = "Costa Rica",
  "Biolley"                              = "Costa Rica",
  "Brunca"                               = "Costa Rica",
  "Brunca Growing Region"                = "Costa Rica",
  "Brunca Region"                        = "Costa Rica",
  "Canton De Desamparados"               = "Costa Rica",
  "Canton Lomas De San Marcelino"        = "Costa Rica",
  "Cantón El Tunel"                      = "Costa Rica",
  "Carrillos Alto De Poás"               = "Costa Rica",
  "Cartago Province"                     = "Costa Rica",
  "Central Costa Rica"                   = "Costa Rica",
  "Central Valley"                       = "Costa Rica",
  "Chirripo Region"                      = "Costa Rica",
  "Chirripó"                             = "Costa Rica",
  "Copey District"                       = "Costa Rica",
  "Coto Brus"                            = "Costa Rica",
  "Dota"                                 = "Costa Rica",
  "El Guarco"                            = "Costa Rica",
  "Las Flores"                           = "Costa Rica",
  "Llano Bonito"                         = "Costa Rica",
  "Llano Bonito De Narajo"               = "Costa Rica",
  "Los Santos"                           = "Costa Rica",
  "Lourdes De Naranjo"                   = "Costa Rica",
  "Mercedes Sur"                         = "Costa Rica",
  "Monte Verde"                          = "Costa Rica",
  "Monteverde"                           = "Costa Rica",
  "Naranjo"                              = "Costa Rica",
  "Poás Volcano Region"                  = "Costa Rica",
  "Puntarenas"                           = "Costa Rica",
  "Puntarenas Province"                  = "Costa Rica",
  "Rivas District"                       = "Costa Rica",
  "Rosario De Desamparados"              = "Costa Rica",
  "Sabanilla De Alajuela"                = "Costa Rica",
  "Sabanilla De Alajuela Growing Region" = "Costa Rica",
  "San Isidro"                           = "Costa Rica",
  "San Jose"                             = "Costa Rica",
  "San José"                             = "Costa Rica",
  "San Jose De Minas"                    = "Costa Rica",
  "San José De Minas"                    = "Costa Rica",
  "San Vito"                             = "Costa Rica",
  "Santa Maria De Dota"                  = "Costa Rica",
  "Southern Costa Rica"                  = "Costa Rica",
  "Tarrazu"                              = "Costa Rica",
  "Tarrazu Growing Region"               = "Costa Rica",
  "Tarrazú"                              = "Costa Rica",
  "Tarrazú Growing Region"               = "Costa Rica",
  "Tobosi"                               = "Costa Rica",
  "Turrubares"                           = "Costa Rica",
  "West Valley"                          = "Costa Rica",
  
  # ── DEMOCRATIC REPUBLIC OF CONGO ─────────────────────────────────────────────
  "Kalehe"                               = "Democratic Republic of Congo",
  "Katanga"                              = "Democratic Republic of Congo",
  "Kirumba"                              = "Democratic Republic of Congo",
  "North Kivu Province"                  = "Democratic Republic of Congo",
  "South Kivu"                           = "Democratic Republic of Congo",
  "South Kivu Growing Region"            = "Democratic Republic of Congo",
  "South Kivu Province"                  = "Democratic Republic of Congo",
  
  # ── DOMINICAN REPUBLIC ───────────────────────────────────────────────────────
  "Dominican Republic"                   = "Dominican Republic",
  "Jarabacoa"                            = "Dominican Republic",
  
  # ── EAST TIMOR ───────────────────────────────────────────────────────────────
  "East Timor"                           = "East Timor",
  
  # ── ECUADOR ──────────────────────────────────────────────────────────────────
  "Chimborazo"                           = "Ecuador",
  "Chimborazo Province"                  = "Ecuador",
  "Galapagos Islands"                    = "Ecuador",
  "Ibarra"                               = "Ecuador",
  "Imbabura Province"                    = "Ecuador",
  "Isla Santa Cruz And Isla San Cristóbal" = "Ecuador",
  "Loja"                                 = "Ecuador",
  "Loja Province"                        = "Ecuador",
  "Loja Region"                          = "Ecuador",
  "North-Central Ecuador"                = "Ecuador",
  "Northern Ecuador"                     = "Ecuador",
  "Pallatanga"                           = "Ecuador",
  "Pichincha"                            = "Ecuador",
  "Pichincha Growing Region"             = "Ecuador",
  "Pichincha Province"                   = "Ecuador",
  "Pinchincha"                           = "Ecuador",
  "Quilanga"                             = "Ecuador",
  "Quito"                                = "Ecuador",
  "Saraguro"                             = "Ecuador",
  "Southern Ecuador"                     = "Ecuador",
  "Zamora Chinchipe"                     = "Ecuador",
  "Zamora Province"                      = "Ecuador",
  "San Cristobal"                        = "Ecuador",
  
  # ── EL SALVADOR ──────────────────────────────────────────────────────────────
  "Ahuachapan"                           = "El Salvador",
  "Ahuachapán Department"                = "El Salvador",
  "Alotepec-Metapan Region"              = "El Salvador",
  "Apaneca"                              = "El Salvador",
  "Apaneca Ilamatepec Mountain Range"    = "El Salvador",
  "Apaneca-Ilamatepec Growing Region"    = "El Salvador",
  "Apaneca-Ilamatepec Mountain Range"    = "El Salvador",
  "Calzontes Arriba"                     = "El Salvador",
  "Chalatenango"                         = "El Salvador",
  "Chalatenango Department"              = "El Salvador",
  "Chalatenango Growing Region"          = "El Salvador",
  "El Boquerón Growing Region"           = "El Salvador",
  "Juayua"                               = "El Salvador",
  "La Unión Department"                  = "El Salvador",
  "La Union"                             = "El Salvador",
  "Los Naranjos"                         = "El Salvador",
  "Metapan"                              = "El Salvador",
  "Northwest El Salvador"                = "El Salvador",
  "Northwestern El Salvador"             = "El Salvador",
  "Santa Ana Department"                 = "El Salvador",
  "Santa Ana Region"                     = "El Salvador",
  "Santa Elena"                          = "El Salvador",
  "Santa Rosa"                           = "El Salvador",
  "Santiago De María"                    = "El Salvador",
  "Southeastern El Salvador"             = "El Salvador",
  "Tecapa Chinameca Growing Region"      = "El Salvador",
  "Volcán Santa Ana"                     = "El Salvador",
  
  # ── ETHIOPIA ─────────────────────────────────────────────────────────────────
  "Agaro District"                       = "Ethiopia",
  "Agaro Gera"                           = "Ethiopia",
  "Aleta Wondo"                          = "Ethiopia",
  "Amhara Region"                        = "Ethiopia",
  "Ana Sora District"                    = "Ethiopia",
  "Arbegona"                             = "Ethiopia",
  "Banti Nenga"                          = "Ethiopia",
  "Bench Maji Zone"                      = "Ethiopia",
  "Bench-Maji Zone"                      = "Ethiopia",
  "Bensa District"                       = "Ethiopia",
  "Bita Genet District"                  = "Ethiopia",
  "Bona Zuria"                           = "Ethiopia",
  "Bombe Mountains"                      = "Ethiopia",
  "Bombe Village"                        = "Ethiopia",
  "Borena Hagermariam District"          = "Ethiopia",
  "Bule Hora District"                   = "Ethiopia",
  "Bure Woreda"                          = "Ethiopia",
  "Chelchele"                            = "Ethiopia",
  "Djimma"                               = "Ethiopia",
  "Djimma Growing Region"                = "Ethiopia",
  "Djimmah"                              = "Ethiopia",
  "Ethiopia Natural Yirgacheffe Adado Shara" = "Ethiopia",
  "Gedeb"                                = "Ethiopia",
  "Gedeb District"                       = "Ethiopia",
  "Gedeo"                                = "Ethiopia",
  "Gedeo Zone"                           = "Ethiopia",
  "Gerbicho Rogicha"                     = "Ethiopia",
  "Guji"                                 = "Ethiopia",
  "Guji Zone"                            = "Ethiopia",
  "Hambela Dimtu"                        = "Ethiopia",
  "Hambela District"                     = "Ethiopia",
  "Hambela Wamena"                       = "Ethiopia",
  "Hambela Wamena District"              = "Ethiopia",
  "Hambela Wamena Woreda"                = "Ethiopia",
  "Hayisa Village"                       = "Ethiopia",
  "Idamo (Also Sidama) Growing Region"   = "Ethiopia",
  "Illubabor Zone"                       = "Ethiopia",
  "Jimma Growing Region"                 = "Ethiopia",
  "Jimma Zone"                           = "Ethiopia",
  "Keffa Zone"                           = "Ethiopia",
  "Kebele Buku Sayisa"                   = "Ethiopia",
  "Keramo Village"                       = "Ethiopia",
  "Kochere"                              = "Ethiopia",
  "Kochere District"                     = "Ethiopia",
  "Kochere Woreda"                       = "Ethiopia",
  "Konga Village"                        = "Ethiopia",
  "Limu Woreda"                          = "Ethiopia",
  "Nensebo Woreda"                       = "Ethiopia",
  "Ochere Woreda"                        = "Ethiopia",
  "Odo Shakiso District"                 = "Ethiopia",
  "Oromia"                               = "Ethiopia",
  "Oromia Growing Region"                = "Ethiopia",
  "Oromia Region"                        = "Ethiopia",
  "Oromia State"                         = "Ethiopia",
  "Shakiso District"                     = "Ethiopia",
  "Sidama"                               = "Ethiopia",
  "Sidama (Also Sidamo) Growing Region"  = "Ethiopia",
  "Sidama (Also Sidamo) Region"          = "Ethiopia",
  "Sidama Growing Region"                = "Ethiopia",
  "Sidama Region"                        = "Ethiopia",
  "Sidama Zone"                          = "Ethiopia",
  "Sidamo"                               = "Ethiopia",
  "Sidamo (Also Sidama)"                 = "Ethiopia",
  "Sidamo (Also Sidama) Growing Region"  = "Ethiopia",
  "Sidamo Growing Region"                = "Ethiopia",
  "Sidamo Zone"                          = "Ethiopia",
  "Snnp Region"                          = "Ethiopia",
  "South-Central Ethiopia"               = "Ethiopia",
  "Southern Ethiopia"                    = "Ethiopia",
  "Southwest Ethiopia"                   = "Ethiopia",
  "Southwestern Ethiopia"                = "Ethiopia",
  "Tore Village"                         = "Ethiopia",
  "Uraga"                                = "Ethiopia",
  "Uraga District"                       = "Ethiopia",
  "West Guji Zone"                       = "Ethiopia",
  "Western Guji"                         = "Ethiopia",
  "Worka Chelbessa"                      = "Ethiopia",
  "Worka-Sakaro"                         = "Ethiopia",
  "Yirgacheffe"                          = "Ethiopia",
  "Yirgacheffe Growing Region"           = "Ethiopia",
  "Yirgachefffe Growing Region"          = "Ethiopia",
  "Yirgacheffe Growing Region"           = "Ethiopia",
  
  # ── GUATEMALA ────────────────────────────────────────────────────────────────
  "Acatenango"                           = "Guatemala",
  "Acatenango Growing Region"            = "Guatemala",
  "Acatenango Valley"                    = "Guatemala",
  "Alotenango"                           = "Guatemala",
  "Antigua"                              = "Guatemala",
  "Antigua Growing Region"               = "Guatemala",
  "Atitlán Growing Region"               = "Guatemala",
  "Central Guatemala"                    = "Guatemala",
  "Chimaltenango"                        = "Guatemala",
  "Chimaltenango Department"             = "Guatemala",
  "Coban"                                = "Guatemala",
  "Cobán"                                = "Guatemala",
  "Cobán Growing Region"                 = "Guatemala",
  "Concepción Huista"                    = "Guatemala",
  "El Diamante"                          = "Guatemala",
  "El Progreso"                          = "Guatemala",
  "El Progreso Department"               = "Guatemala",
  "El Progresso"                         = "Guatemala",
  "El Progresso Department"              = "Guatemala",
  "Fraijanes"                            = "Guatemala",
  "Fraijanes Growing Region"             = "Guatemala",
  "Fraijanes Plateau"                    = "Guatemala",
  "Fraijanes Plateau Growing Region"     = "Guatemala",
  "Guatemala Department"                 = "Guatemala",
  "Huehuetenango"                        = "Guatemala",
  "Huehuetenango Department"             = "Guatemala",
  "Huehuetenango Growing Region"         = "Guatemala",
  "Huehuetenengo Department"             = "Guatemala",
  "Jalapa"                               = "Guatemala",
  "Jutiapa Department"                   = "Guatemala",
  "La Libertad"                          = "Guatemala",
  "Lake Amatitlán Area"                  = "Guatemala",
  "Lake Amatitlán Region"                = "Guatemala",
  "Lake Atitlan"                         = "Guatemala",
  "Lake Atitlán Growing Region"          = "Guatemala",
  "Los Altos"                            = "Guatemala",
  "New Oriente Growing Region"           = "Guatemala",
  "Northern Guatemala"                   = "Guatemala",
  "Palencia"                             = "Guatemala",
  "Quiché"                               = "Guatemala",
  "Region Concepción Huista"             = "Guatemala",
  "San Cristobal Acasaguastlán"          = "Guatemala",
  "San Cristobal Cucho"                  = "Guatemala",
  "San Juan La Laguna"                   = "Guatemala",
  "San Lorenzo"                          = "Guatemala",
  "San Lucas Tolimán"                    = "Guatemala",
  "San Marcos Department"                = "Guatemala",
  "San Martin Jilotepeque"               = "Guatemala",
  "Santa Barbara"                        = "Guatemala",
  "Santa Rosa Growing Region"            = "Guatemala",
  "Sierra De Las Minas"                  = "Guatemala",
  "Sololá"                               = "Guatemala",
  "South-Central Guatemala"              = "Guatemala",
  "Suchitan"                             = "Guatemala",
  "Tojquia"                              = "Guatemala",
  "Villa Canales"                        = "Guatemala",
  "Alta Verapaz"                         = "Guatemala",
  "Alta Verapaz Department"              = "Guatemala",
  "Conganama"                            = "Guatemala",
  "Congonama"                            = "Guatemala",
  
  # ── HAITI ────────────────────────────────────────────────────────────────────
  "Cap Haitien"                          = "Haiti",
  "Central Plateau"                      = "Haiti",
  "Dondon"                               = "Haiti",
  "Savane Zombie"                        = "Haiti",
  "Thiotte"                              = "Haiti",
  
  # ── HAWAII (USA) ─────────────────────────────────────────────────────────────
  "Big Island Of Hawaii"                 = "USA (Hawaii)",
  "Big Island Of Hawai'I"                = "USA (Hawaii)",
  '\"Big Island\" Of Hawaii'             = "USA (Hawaii)",
  '\"Big Island\" Of Hawai\'I'           = "USA (Hawaii)",
  '"Big Island" Of Hawaii'               = "USA (Hawaii)",
  '"Big Island" Of Hawai\'I'             = "USA (Hawaii)",
  "Captain Cook"                         = "USA (Hawaii)",
  "Hawaii"                               = "USA (Hawaii)",
  "Holualoa"                             = "USA (Hawaii)",
  "Iambu Growing Region"                 = "USA (Hawaii)",
  "Island Of Maui"                       = "USA (Hawaii)",
  "Ka'U District"                        = "USA (Hawaii)",
  "Ka'U Growing District"                = "USA (Hawaii)",
  "Ka'U Growing Region"                  = "USA (Hawaii)",
  "Ka'Ū"                                 = "USA (Hawaii)",
  "Ka'Ū Growing Region"                  = "USA (Hawaii)",
  "Ka'U"                                 = "USA (Hawaii)",
  "Kainaliu"                             = "USA (Hawaii)",
  "Kalaheo"                              = "USA (Hawaii)",
  "Kauai"                                = "USA (Hawaii)",
  "Kealakekua"                           = "USA (Hawaii)",
  "Kealakekua Growing Region"            = "USA (Hawaii)",
  "Kona"                                 = "USA (Hawaii)",
  "Kona District"                        = "USA (Hawaii)",
  "Kona Growing District"                = "USA (Hawaii)",
  "Kona Growing Region"                  = "USA (Hawaii)",
  "Kurtistown"                           = "USA (Hawaii)",
  "Maunawili Growing Region"             = "USA (Hawaii)",
  "North Kona"                           = "USA (Hawaii)",
  "North Kona Growing District"          = "USA (Hawaii)",
  "Puna"                                 = "USA (Hawaii)",
  "Puna District"                        = "USA (Hawaii)",
  "Puna Growing Region"                  = "USA (Hawaii)",
  "Southeastern Oahu"                    = "USA (Hawaii)",
  "South Kona Growing Region"            = "USA (Hawaii)",
  "Wood Valley"                          = "USA (Hawaii)",
  
  # ── HONDURAS ─────────────────────────────────────────────────────────────────
  "Comayagua"                            = "Honduras",
  "Comayagua Department"                 = "Honduras",
  "Copan"                                = "Honduras",
  "Corquin"                              = "Honduras",
  "Intibucá Department"                  = "Honduras",
  "La Paz"                               = "Honduras",
  "La Paz Department"                    = "Honduras",
  "Lempira Department"                   = "Honduras",
  "Marcala"                              = "Honduras",
  "Marcala Growing Region"               = "Honduras",
  "Masaguara"                            = "Honduras",
  "Ocotepeque Department"                = "Honduras",
  "Sandy Bay Valley"                     = "Honduras",
  "Santa Barbara Department"             = "Honduras",
  "Santa Bárbara"                        = "Honduras",
  "Siguatepeque"                         = "Honduras",
  
  # ── INDIA ────────────────────────────────────────────────────────────────────
  "Blue Pine Forest"                     = "India",
  
  # ── INDONESIA ────────────────────────────────────────────────────────────────
  "Aceh"                                 = "Indonesia",
  "Aceh Growing Region"                  = "Indonesia",
  "Aceh Province"                        = "Indonesia",
  "Aceh Tengah"                          = "Indonesia",
  "Bali"                                 = "Indonesia",
  "Bebesen District"                     = "Indonesia",
  "Belis"                                = "Indonesia",
  "East Malaysia"                        = "Indonesia",
  "Flores And Sumatra"                   = "Indonesia",
  "Flores Island"                        = "Indonesia",
  "Gayo"                                 = "Indonesia",
  "Gayo (Also Aceh) Growing Region"      = "Indonesia",
  "Gunung Tujuh"                         = "Indonesia",
  "Indonesia"                            = "Indonesia",
  "Jambi Province"                       = "Indonesia",
  "Java"                                 = "Indonesia",
  "Kerinci"                              = "Indonesia",
  "Kerinci Highlands"                    = "Indonesia",
  "Lincong"                              = "Indonesia",
  "Lintong Growing Region"               = "Indonesia",
  "Lintongnihuta"                        = "Indonesia",
  "Mandheling Growing Region"            = "Indonesia",
  "Mount Kerinci Highlands"              = "Indonesia",
  "North Sumatra Province"               = "Indonesia",
  "Northern Sumatra"                     = "Indonesia",
  "Northern Sumatra Indonesia"           = "Indonesia",
  "Pantan Musara"                        = "Indonesia",
  "Panchia"                              = "Indonesia",
  "Pematang Purba"                       = "Indonesia",
  "Sabah State"                          = "Indonesia",
  "Simalungun"                           = "Indonesia",
  "Simalungun Regency"                   = "Indonesia",
  "South-Central Sulawesi"               = "Indonesia",
  "Toraja Growing Region"                = "Indonesia",
  
  # ── JAMAICA ──────────────────────────────────────────────────────────────────
  "Blue Mountain Growing Region"         = "Jamaica",
  "Eastern Jamaica."                     = "Jamaica",
  
  # ── KENYA ────────────────────────────────────────────────────────────────────
  "Bungoma"                              = "Kenya",
  "Bungoma Region"                       = "Kenya",
  "Central Kenya"                        = "Kenya",
  "Eastern Province"                     = "Kenya",
  "Eastern Province Kenya"               = "Kenya",
  "Embu"                                 = "Kenya",
  "Embu County"                          = "Kenya",
  "Gatundu"                              = "Kenya",
  "Gichugu Division"                     = "Kenya",
  "Kiambi County"                        = "Kenya",
  "Kiambu County"                        = "Kenya",
  "Kiambu Growing Region"                = "Kenya",
  "Kirinyaga"                            = "Kenya",
  "Kirinyaga County"                     = "Kenya",
  "Kirinyaga District"                   = "Kenya",
  "Kisii"                                = "Kenya",
  "Kericho County"                       = "Kenya",
  "Mathira West District"                = "Kenya",
  "Mount Kenya Growing Region"           = "Kenya",
  "Murang'A County"                      = "Kenya",
  "Muranga County"                       = "Kenya",
  "Muranga District"                     = "Kenya",
  "Murutra"                              = "Kenya",
  "Nakuru County"                        = "Kenya",
  "Nakuru Province"                      = "Kenya",
  "Ngiriambu District"                   = "Kenya",
  "Nyeri County"                         = "Kenya",
  "Nyeri Growing Region"                 = "Kenya",
  "Rift Valley Region"                   = "Kenya",
  "South-Central Kenya"                  = "Kenya",
  "Southwestern Kenya"                   = "Kenya",
  "Thika Growing Region"                 = "Kenya",
  "Thika Plateau"                        = "Kenya",
  "Thika Province"                       = "Kenya",
  "Western Kenya"                        = "Kenya",
  
  # ── MADAGASCAR ───────────────────────────────────────────────────────────────
  "Antón Montañita"                      = "Madagascar",
  
  # ── MALAYSIA ─────────────────────────────────────────────────────────────────
  "Kwazulu-Natal Province"               = "South Africa",
  
  # ── MEXICO ───────────────────────────────────────────────────────────────────
  "Chiapas"                              = "Mexico",
  "Chiapas State"                        = "Mexico",
  "Chaguites"                            = "Mexico",
  "Coatepec"                             = "Mexico",
  "Coatepeque"                           = "Mexico",
  "Guerrero State"                       = "Mexico",
  "Miahuatlán"                           = "Mexico",
  "Motozintla De Mendoza"                = "Mexico",
  "Oaxaca"                               = "Mexico",
  "Oaxaca State"                         = "Mexico",
  "Pluma Hidalgo"                        = "Mexico",
  "Sierra Madre"                         = "Mexico",
  "Veracruz"                             = "Mexico",
  "Veracruz State"                       = "Mexico",
  "Yautepec"                             = "Mexico",
  "Yautepec/Miahuatlan"                  = "Mexico",
  
  # ── NEPAL ────────────────────────────────────────────────────────────────────
  "Bhirkune Village"                     = "Nepal",
  "Nuwakot District"                     = "Nepal",
  
  # ── NICARAGUA ────────────────────────────────────────────────────────────────
  "Dipilto"                              = "Nicaragua",
  "Jinotega"                             = "Nicaragua",
  "Jinotega Department"                  = "Nicaragua",
  "La Dalia"                             = "Nicaragua",
  "Matagalpa"                            = "Nicaragua",
  "Matagalpa Department"                 = "Nicaragua",
  "Matagalpa Growing Region"             = "Nicaragua",
  "Nueva Segovia"                        = "Nicaragua",
  "Nueva Segovia Growing Region"         = "Nicaragua",
  "Nueva Suiza"                          = "Nicaragua",
  
  # ── PANAMA ───────────────────────────────────────────────────────────────────
  "Alto Quiel"                           = "Panama",
  "Boquete"                              = "Panama",
  "Boquete Growing Region"               = "Panama",
  "Chiriqui"                             = "Panama",
  "Chiriqui Growing Region"              = "Panama",
  "Chiriqui Province"                    = "Panama",
  "Chiriquí"                             = "Panama",
  "Chiriquí Province"                    = "Panama",
  "Far Western Panama"                   = "Panama",
  "Horcheta"                             = "Panama",
  "Horqueta"                             = "Panama",
  "Jaramillo"                            = "Panama",
  "Paso Ancho"                           = "Panama",
  "Piedra Candela"                       = "Panama",
  "Potrerillo Arriba"                    = "Panama",
  "Renacimiento"                         = "Panama",
  "Renacimiento District"                = "Panama",
  "Santa Elena Province"                 = "Panama",
  "Tierras Altas"                        = "Panama",
  "Volcan"                               = "Panama",
  "Volcan Growing Region"                = "Panama",
  "Volcano"                              = "Panama",
  "Volcán Growing Region"                = "Panama",
  "Western Panama"                       = "Panama",
  
  # ── PAPUA NEW GUINEA ─────────────────────────────────────────────────────────
  "Ainantu District"                     = "Papua New Guinea",
  "Banz"                                 = "Papua New Guinea",
  "Eastern Highlands"                    = "Papua New Guinea",
  "Eastern Highlands Province"           = "Papua New Guinea",
  "Jiawaka Province"                     = "Papua New Guinea",
  "Jiwaka Province"                      = "Papua New Guinea",
  "Kabiufa"                              = "Papua New Guinea",
  "Kainantu District"                    = "Papua New Guinea",
  "Purosa Village"                       = "Papua New Guinea",
  "Upper Waghi Valley"                   = "Papua New Guinea",
  "Wenango District"                     = "Papua New Guinea",
  "Western Highlands"                    = "Papua New Guinea",
  "Western Highlands Province"           = "Papua New Guinea",
  
  # ── PERU ─────────────────────────────────────────────────────────────────────
  "Amazonas Region"                      = "Peru",
  "Amaybamba"                            = "Peru",
  "Atok"                                 = "Peru",
  "Cajamarca"                            = "Peru",
  "Cajamarca Growing Region"             = "Peru",
  "Cajamarca Region"                     = "Peru",
  "Chinchipe"                            = "Peru",
  "Chirinos"                             = "Peru",
  "Cusco"                                = "Peru",
  "Cusco Department"                     = "Peru",
  "Cusco Province"                       = "Peru",
  "Cusco Region"                         = "Peru",
  "Huabal"                               = "Peru",
  "Huarango"                             = "Peru",
  "Jaen"                                 = "Peru",
  "Jaén"                                 = "Peru",
  "Jaén Province"                        = "Peru",
  "Junin"                                = "Peru",
  "Junin Region"                         = "Peru",
  "Junín Province"                       = "Peru",
  "La Cañada"                            = "Peru",
  "La Coipa"                             = "Peru",
  "La Convención Province"               = "Peru",
  "Northern Peru"                        = "Peru",
  "Oxampampa"                            = "Peru",
  "Oxapampa"                             = "Peru",
  "Oxapampa Province"                    = "Peru",
  "Pacaybamba Growing Region"            = "Peru",
  "Pasco Department"                     = "Peru",
  "Pasco Growing Region"                 = "Peru",
  "Puno"                                 = "Peru",
  "San Ignacio"                          = "Peru",
  "San Ignacio Province"                 = "Peru",
  "Sandia Valley"                        = "Peru",
  "Satipo Province"                      = "Peru",
  "Tabaconas"                            = "Peru",
  "Tres Cruces"                          = "Peru",
  "Utcubamba Province"                   = "Peru",
  "Villa Rica"                           = "Peru",
  "Villa Rica District"                  = "Peru",
  
  # ── PHILIPPINES ──────────────────────────────────────────────────────────────
  "Benguet"                              = "Philippines",
  "Benguet Province"                     = "Philippines",
  "Bukidnon"                             = "Philippines",
  
  # ── RWANDA ───────────────────────────────────────────────────────────────────
  "Boneza"                               = "Rwanda",
  "Buhoma"                               = "Rwanda",
  "Central Rwanda"                       = "Rwanda",
  "Gakenke"                              = "Rwanda",
  "Gakenke District"                     = "Rwanda",
  "Gakenke Growing Region"               = "Rwanda",
  "Gikongoro Prefecture"                 = "Rwanda",
  "Huye"                                 = "Rwanda",
  "Huye District"                        = "Rwanda",
  "Kabuye"                               = "Rwanda",
  "Karongi District"                     = "Rwanda",
  "Karundu"                              = "Rwanda",
  "Lake Kivu"                            = "Rwanda",
  "Muhanga"                              = "Rwanda",
  "Muhanga District"                     = "Rwanda",
  "Musasa"                               = "Rwanda",
  "Mukaro"                               = "Rwanda",
  "Namasheke District"                   = "Rwanda",
  "Nyakibanda"                           = "Rwanda",
  "Nyamagabe District"                   = "Rwanda",
  "Nyamasheke"                           = "Rwanda",
  "Nyamasheke District"                  = "Rwanda",
  "Nyarita"                              = "Rwanda",
  "Nyaruguru District"                   = "Rwanda",
  "Rulindo"                              = "Rwanda",
  "Rulindo District"                     = "Rwanda",
  "Rustiro District"                     = "Rwanda",
  "Rutsiro"                              = "Rwanda",
  "Rutsiro District"                     = "Rwanda",
  "South-Central Rwanda"                 = "Rwanda",
  "Southern Province"                    = "Rwanda",
  "Southern Rwanda"                      = "Rwanda",
  "Western Province"                     = "Rwanda",
  "Western Rwanda"                       = "Rwanda",
  
  # ── SAINT HELENA ─────────────────────────────────────────────────────────────
  "Saint Helena Island"                  = "Saint Helena",
  
  # ── TAIWAN ───────────────────────────────────────────────────────────────────
  "Alishan"                              = "Taiwan",
  "Alishan Township"                     = "Taiwan",
  "Chia-Yi"                              = "Taiwan",
  "Chia-Yi City"                         = "Taiwan",
  "Chiayi County"                        = "Taiwan",
  "Chaiyi"                               = "Taiwan",
  "Pingtung"                             = "Taiwan",
  "Sun Moon Lake"                        = "Taiwan",
  "Taitung Luan Mountain"                = "Taiwan",
  "Yunlin"                               = "Taiwan",
  
  # ── TANZANIA ─────────────────────────────────────────────────────────────────
  "Arusha Region"                        = "Tanzania",
  "Karatu"                               = "Tanzania",
  "Mara Growing Region"                  = "Tanzania",
  "Mara Region"                          = "Tanzania",
  "Mbeya"                                = "Tanzania",
  "Mbeya Growing Region"                 = "Tanzania",
  "Mbozi"                                = "Tanzania",
  "Mbozi District"                       = "Tanzania",
  "Ngila Estate"                         = "Tanzania",
  "Ngorogoro"                            = "Tanzania",
  "Ngorongoro"                           = "Tanzania",
  "Ngorongoro Conservation Area"         = "Tanzania",
  "Ngorongoro Crater Region"             = "Tanzania",
  "Northern Tanzania"                    = "Tanzania",
  "Songwe Region"                        = "Tanzania",
  "Southwestern Tanzania"                = "Tanzania",
  "Tarime"                               = "Tanzania",
  "Tarime District"                      = "Tanzania",
  
  # ── THAILAND ─────────────────────────────────────────────────────────────────
  "Chiang Mai Province"                  = "Thailand",
  "Chiang Rai"                           = "Thailand",
  "Chiang Rai Province"                  = "Thailand",
  "Chumphon"                             = "Thailand",
  "Doi Pangkhon"                         = "Thailand",
  "Doi Pangkhon Growing Region"          = "Thailand",
  "Huai Mae Liam"                        = "Thailand",
  "Nan Province"                         = "Thailand",
  "Northern Thailand"                    = "Thailand",
  "Omkoi District"                       = "Thailand",
  "Tha Sae"                              = "Thailand",
  
  # ── UGANDA ───────────────────────────────────────────────────────────────────
  "Bugisu Region"                        = "Uganda",
  "Kapchorwa District"                   = "Uganda",
  "Sipi Falls"                           = "Uganda",
  "Southwest Uganda"                     = "Uganda",
  
  # ── VIETNAM ──────────────────────────────────────────────────────────────────
  "Cau Dat"                              = "Vietnam",
  "Central Highlands"                    = "Vietnam",
  "Dalat"                                = "Vietnam",
  "Lam Dong Province"                    = "Vietnam",
  "Southwest Vietnam"                    = "Vietnam",
  
  # ── YEMEN ────────────────────────────────────────────────────────────────────
  "Al Hayma District"                    = "Yemen",
  "Al Hayma Region"                      = "Yemen",
  "Al Mahjr"                             = "Yemen",
  "Al Mashtal Ul Burhani"                = "Yemen",
  "Al Wadi Region"                       = "Yemen",
  "Al-Durrar"                            = "Yemen",
  "Al-Haimah"                            = "Yemen",
  "Bani Matar"                           = "Yemen",
  "Bani Matar Growing Region"            = "Yemen",
  "Central Yemen"                        = "Yemen",
  "Haraaz"                               = "Yemen",
  "Haraaz Growing Region"                = "Yemen",
  "Harar (Also Harrar) Growing Region Of Eastern Ethiopia" = "Ethiopia",
  "Haraz Growing Region"                 = "Yemen",
  "Hayma Dakhiliya Growing Region"       = "Yemen",
  "Jabal Haraz"                          = "Yemen",
  "Llayla District"                      = "Yemen",
  "North-Central Yemen"                  = "Yemen",
  "Sa'Dah Governorate"                   = "Yemen",
  "Sama"                                 = "Yemen",
  "Sana'A Governorate"                   = "Yemen",
  "Sana'A Growing Region"                = "Yemen",
  "Sharqi"                               = "Yemen",
  
  # ── ZAMBIA ───────────────────────────────────────────────────────────────────
  "Isoka"                                = "Zambia",
  
  # ── DATA / LABEL ARTEFACTS (not origins) ────────────────────────────────────
  "Fruity & Vibrant"                     = NA_character_,
  "Medium-Light"                         = NA_character_,
  "Sweet & Comforting"                   = NA_character_,
  "Finca Santa Teresa"                   = NA_character_   # ambiguous without country
)


# ------------------------------------------------------------------------------
# 3.  Helper: normalise a string then look it up
# ------------------------------------------------------------------------------
lookup_country <- function(x) {
  # Normalise: trim whitespace, collapse multiple spaces
  key <- trimws(gsub("\\s+", " ", x))
  # Direct lookup (case-sensitive — keys above are already title-cased from CSV)
  country <- region_to_country[key]
  if (!is.na(country)) return(unname(country))
  # Fallback: return original value flagged as unmapped
  return(paste0("UNMAPPED: ", key))
}


# ------------------------------------------------------------------------------
# 4.  Apply to both origin columns
# ------------------------------------------------------------------------------
d <- d |>
  mutate(
    country_1 = sapply(origin_1, lookup_country),
    country_2 = sapply(origin_2, lookup_country)
  )


# ------------------------------------------------------------------------------
# 5.  QA – print any unmapped values so you can extend the lookup table
# ------------------------------------------------------------------------------
unmapped <- unique(c(
  d$country_1[grepl("^UNMAPPED:", d$country_1)],
  d$country_2[grepl("^UNMAPPED:", d$country_2)]
))

if (length(unmapped) > 0) {
  cat("⚠️  Unmapped values (extend region_to_country to fix):\n")
  cat(paste(" -", unmapped), sep = "\n")
} else {
  cat("✅  All origin values mapped successfully.\n")
}


# ------------------------------------------------------------------------------
# 6.  Save enriched dataset
# ------------------------------------------------------------------------------
write.csv(d, "Question1/data/regions_with_countries.csv", row.names = FALSE)
cat("\nSaved → regions_with_countries.csv\n")
cat("Columns added: country_1, country_2\n")

d
}